version: "3.1"

services:
  migrations:
    build: ./../migrations
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=octo_palm
      - DB_USERNAME=admin
      - DB_PASSWORD=password
