version: "3.1"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=octo_palm
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  migrations:
    build: ./../migrations
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=octo_palm
      - DB_USERNAME=admin
      - DB_PASSWORD=password
    depends_on:
      - db